apiVersion: v1
kind: Service
metadata:
  name: feedapi-service
  namespace: kwetter
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8104
      targetPort: 8104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: feedapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: feedapi-pod
        version: latest
    spec:
      containers:
      - name: feedapi-container
        image: docker.io/timdus/feedapi:latest
        ports:
        - containerPort: 8104
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"