apiVersion: v1
kind: Service
metadata:
  name: feeddb
  namespace: kwetter
spec:
  selector:
    app: feeddb
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feeddb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feeddb
  template:
    metadata:
      labels:
        app: feeddb
    spec:
      containers:
        - name: feeddb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 8004
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Test123!"