apiVersion: v1
kind: Service
metadata:
  name: feedapi-service
  labels:
    app: feedapi
    service: feedapi-service
spec:
  selector:
    app: feedapi-pod
  ports:
    - protocol: TCP
      name: http
      port: 8104
      targetPort: 8104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapi
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: feedapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: feedapi-pod
        version: latest
    spec:
      containers:
      - name: feedapi-container
        image: timdus/feedapi:latest
        ports:
        - containerPort: 8104
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"