# apiVersion: datadoghq.com/v2alpha1
# kind: DatadogAgent
# metadata:
#   name: datadog
# spec:
#   global:
#     clusterName: kwetter
#     site: datadoghq.eu
#     credentials:
#       apiSecret:
#         secretName: datadog-secret
#         keyName: api-key
#       appSecret:
#         secretName: datadog-secret
#         keyName: app-key
#   features:
#     liveContainerCollection:
#       enabled: true
#     orchestratorExplorer:
#       enabled: true
#   override:
#     agents:
#       containers:
#         processAgent:
#           env:
#             - name: "DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS"
#               value: "tag1:*"
#     clusterAgent:
#       env:
#         - name: "DD_ORCHESTRATOR_EXPLORER_EXTRA_TAGS"
#           value: "tag1:*"