apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: kwetter
  labels:
    app: apigateway
    service: kweetapi
spec:
  selector:
    app: apigateway-pod
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 7100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: apigateway-pod
      version: latest
  template:
    metadata:
      labels:
        app: apigateway-pod
        version: latest
    spec:
      containers:
      - name: apigateway-container
        image: docker.io/timdus/apigateway:latest
        ports:
        - containerPort: 7100
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"