apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kweetapi-autoscaler
  namespace: kwetter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kweetapi
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50