apiVersion: v1
kind: Service
metadata:
  name: kweetapi-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 7101
      targetPort: 7101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kweetapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: kweetapi-pod
        version: latest
    spec:
      containers:
      - name: kweetapi-container
        image: docker.io/timdus/kweetapi:latest
        ports:
        - containerPort: 7101
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"