apiVersion: v1
kind: Service
metadata:
  name: kweetdb-service
  namespace: kwetter
spec:
  selector:
    app: kweetdb-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kweetdb
  namespace: kwetter
spec:
  serviceName: kweetdb-service
  replicas: 1
  selector:
    matchLabels:
      app: kweetdb-pod
  template:
    metadata:
      labels:
        app: kweetdb-pod
    spec:
      containers:
        - name: kweetdb-container
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              value: Test123!
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: kweet
            - name: PGDATA
              value: /data/pgdata
          resources:
            limits:   
              memory: 512Mi
              cpu: "1"
   # Volume Claim
  volumeClaimTemplates:
  - metadata:
      name: postgresql-db-disk
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi