apiVersion: v1
kind: Service
metadata:
  name: kweetapi
  namespace: kwetter
spec:
  selector:
    app: kweetapi
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kweetapi
      version: latest
  template:
    metadata:
      labels:
        app: kweetapi
        version: latest
    spec:
      containers:
      - name: kweetapi
        image: timdus/kweetapi:latest
        ports:
        - containerPort: 8102
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"