apiVersion: v1
kind: Service
metadata:
  name: kweetdb
  namespace: kwetter
spec:
  selector:
    app: kweetdb
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetdb
  template:
    metadata:
      labels:
        app: kweetdb
    spec:
      containers:
        - name: kweetdb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 8002
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Test123!"