apiVersion: v1
kind: Service
metadata:
  name: kweetapi-service
  namespace: kwetter
  labels:
    app: kweetapi
    service: kweetapi-service
spec:
  selector:
    app: kweetapi-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 8102
      targetPort: 8102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetapi
  namespace: kwetter
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: kweetapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: kweetapi-pod
        version: latest
    spec:
      containers:
      - name: kweetapi-container
        image: timdus/kweetapi:latest
        ports:
        - containerPort: 8102
        readinessProbe:
          exec:
            command:
            - stat
            - /tmp/ready
          initialDelaySeconds: 10
          periodSeconds: 5
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c 
              - "sleep 10"