apiVersion: v1
kind: Service
metadata:
  name: kweetdb
  namespace: kwetter
spec:
  selector:
    app: kweetdb
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 7001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kweetdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kweetdb
  template:
    metadata:
      labels:
        app: kweetdb
    spec:
      containers:
        - name: kweetdb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 7001