version: "3.2"

networks:
  backend:
  frontend:
  rabbitmq:
    

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    command: [ "bash", "-c", "chmod 400 /var/lib/rabbitmq/.erlang.cookie; rabbitmq-server" ]
    networks:
      - rabbitmq
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 10s
        retries: 3

  kweetapi:
    image: timdus/kweetapi:latest
    ports:
      - 8101:80
    networks:
      - backend
      - rabbitmq 
    depends_on:
      - rabbitmq
      - kweetdb

  kweetdb:
    container_name: kweet-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Test123!
    networks:
     - backend
    ports:
     - 8001:1433

  customerapi:
    image: timdus/customerapi:latest
    ports:
      - 8102:80
    networks:
      - backend
      - rabbitmq 
    environment:
     - DB_HOST=customerdb
     - DB_NAME=customer
     - DB_SA_PASSWORD=Test123!
    depends_on:
      - rabbitmq
      - customerdb

  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Test123!
    networks:
     - backend
    ports:
     - 8002:1433

  followapi:
    image: timdus/followapi:latest
    ports:
      - 8103:80
    networks:
      - backend
      - rabbitmq 
    depends_on:
      - rabbitmq
      - followdb

  followdb:
    container_name: follow-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Test123!
    networks:
     - backend
    ports:
     - 8003:1433
  
  feedapi:
    image: timdus/feedapi:latest
    ports:
      - 8104:80
    networks:
      - backend
      - rabbitmq 
    depends_on:
      - rabbitmq
      - feeddb

  feeddb:
    container_name: feed-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Test123!
    networks:
     - backend
    ports:
     - 8004:1433

  apigateway:
    image: timdus/kwettergateway:latest
    ports:
      - 8100:80
    networks:
      - backend
      - frontend