apiVersion: v1
kind: Service
metadata:
  name: followapi
  namespace: kwetter
spec:
  selector:
    app: followapi
  ports:
    - protocol: TCP
      port: 8103
      targetPort: 8103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: followapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: followapi
      version: latest
  template:
    metadata:
      labels:
        app: followapi
        version: latest
    spec:
      containers:
      - name: followapi-container
        image: docker.io/timdus/followapi:latest
        ports:
        - containerPort: 8103
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"