apiVersion: v1
kind: Service
metadata:
  name: followdb-service
  namespace: kwetter
spec:
  selector:
    app: followdb-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: followdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followdb-pod
  template:
    metadata:
      labels:
        app: followdb-pod
    spec:
      containers:
        - name: followdb-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Test123!"