apiVersion: v1
kind: Service
metadata:
  name: followdb
  namespace: kwetter
spec:
  selector:
    app: followdb
  ports:
    - protocol: TCP
      port: 7003
      targetPort: 7003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: followdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followdb
  template:
    metadata:
      labels:
        app: followdb
    spec:
      containers:
        - name: followdb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 7003