apiVersion: v1
kind: Service
metadata:
  name: followapi-service
  labels:
    app: followapi
    service: followapi-service
spec:
  selector:
    app: followapi-pod
  ports:
    - protocol: TCP
      name: http
      port: 8103
      targetPort: 8103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: followapi
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: followapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: followapi-pod
        version: latest
    spec:
      containers:
      - name: followapi-container
        image: timdus/followapi:latest
        ports:
        - containerPort: 8103
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"