apiVersion: v1
kind: Service
metadata:
  name: customerapi
  namespace: kwetter
  labels:
    app: customerapi
    service: customerapi
spec:
  selector:
    app: customerapi
  ports:
    - protocol: TCP
      name: http
      port: 8101
      targetPort: 8101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: customerapi
      version: latest
  template:
    metadata:
      labels:
        app: customerapi
        version: latest
    spec:
      containers:
      - name: customerapi
        image: timdus/customerapi:latest
        ports:
        - containerPort: 8101
        imagePullPolicy: Always
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"