apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 7102
      targetPort: 7102
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi
  namespace: kwetter
spec:
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: customerapi-pod
      version: latest
  template:
    metadata:
      labels:
        app: customerapi-pod
        version: latest
    spec:
      containers:
      - name: customerapi-container
        image: docker.io/timdus/customerapi:latest
        ports:
        - containerPort: 7102
        resources:
          limits:   
            memory: 512Mi
            cpu: "1"