apiVersion: v1
kind: Service
metadata:
  name: customerdb
  namespace: kwetter
spec:
  selector:
    app: customerdb
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerdb
  template:
    metadata:
      labels:
        app: customerdb
    spec:
      containers:
        - name: customerdb
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 8001
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Test123!"