apiVersion: v1
kind: Service
metadata:
  name: customerdb-service
  namespace: kwetter
spec:
  selector:
    app: customerdb-pod
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerdb
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerdb-pod
  template:
    metadata:
      labels:
        app: customerdb-pod
    spec:
      containers:
        - name: customerdb-container
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            value: "Test123!"