name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: timdus

jobs:
  build_customerapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push customerapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/customerapi:old -f ./Kwetter/Services/CustomerService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/customerapi:old

  build_kweetapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push kweetapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kweetapi:old -f ./Kwetter/Services/KweetService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kweetapi:old

  build_followapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push followapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/followapi:old -f ./Kwetter/Services/FollowService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/followapi:old

  build_feedapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push feedapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/feedapi:old -f ./Kwetter/Services/FeedService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/feedapi:old

  build_moderationapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push moderationapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/moderationapi:old -f ./Kwetter/Services/ModerationService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/moderationapi:old

  build_gateway:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push apigateway
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kwettergateway:old -f ./Kwetter/Services/APIGateway/APIGateway/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kwettergateway:old

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push frontend
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kwetterfront:old -f ./Kwetter/frontend/Dockerfile ./Kwetter/frontend
        docker push ${{ env.DOCKERHUB_USERNAME }}/kwetterfront:old
