name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: timdus

jobs:
  build_customerapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push customerapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/customerapi:latest -f ./Kwetter/Services/CustomerService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/customerapi:latest

  build_kweetapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push kweetapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest -f ./Kwetter/Services/KweetService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest

  build_followapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push followapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/followapi:latest -f ./Kwetter/Services/FollowService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/followapi:latest

  build_feedapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push feedapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/feedapi:latest -f ./Kwetter/Services/FeedService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/feedapi:latest

  build_moderationapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push moderationapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/moderationapi:latest -f ./Kwetter/Services/ModerationService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/moderationapi:latest

  build_gateway:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push apigateway
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kwettergateway:latest -f ./Kwetter/Services/APIGateway/APIGateway/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kwettergateway:latest

  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push frontend
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kwetterfront:latest -f ./Kwetter/frontend/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kwetterfront:latest
