name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: timdus
  DOCKERHUB_PASSWORD: dckr_pat_rPGoZ5xSt_esEeWG0mmhn6uZgdA

jobs:
  build_customerapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push customerapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/customerapi:latest -f ./Kwetter/Services/CustomerService/CustomerService.API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/customerapi:latest

  build_kweetapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push kweetapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest -f ./Kwetter/Services/KweetService/KweetService.API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest
