name: Testing KweetApi
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      kweetapi:
        image: timdus/kweetapi:latest
        ports:
          - 8102:8102
          
      mypostgres:
        image: postgres:latest
        ports:
          - 8002:5432
        env:
          POSTGRES_PASSWORD: Test123!
          POSTGRES_USER: postgres
          POSTGRES_DB: kweet
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: ./Kubernetes/LoadTesting/CreateKweet.js 
