name: Build and Push KweetApi

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: timdus

jobs:
  build_kweetapi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build and Push kweetapi
      run: |
        docker build -t ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest -f ./Kwetter/Services/KweetService/API/Dockerfile .
        docker push ${{ env.DOCKERHUB_USERNAME }}/kweetapi:latest
        
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: dotnet test ./Kwetter/Services/KweetService/Test
